# Generated by Django 2.0.2 on 2018-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180216_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
