# Generated by Django 2.0.2 on 2018-02-17 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180217_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
