# Generated by Django 2.0.2 on 2018-02-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180217_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='published',
            field=models.DateField(),
        ),
    ]
