# Generated by Django 2.0.2 on 2018-02-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180216_1623'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryItem',
        ),
    ]
