# Generated by Django 2.0.2 on 2018-02-17 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180216_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
